apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
  labels:
    app: transaction-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
      - name: transaction-management
        image: transaction-management:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-management-service
spec:
  selector:
    app: transaction-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
